import { AllEntities, Entity, PropertiesOf } from 'n8n-workflow';

type ITGlueMap = {
	configuration: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'bulkDestroy';
	domain: 'get';
	organization: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'bulkDestroy' | 'deleteOrganization';
	password: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'bulkDestroy' | 'delete';
	flexibleAsset: 'get' | 'getById' | 'create' | 'update' | 'bulkDestroy' | 'delete';
	contact: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'bulkDestroy' | 'delete';
	attachment: 'create' | 'update' | 'bulkDestroy';
	configurationInterface: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'delete';
	configurationStatus: 'get' | 'getById' | 'create' | 'update';
	configurationType: 'get' | 'getById' | 'create' | 'update';
	contactType: 'get' | 'getById' | 'create' | 'update';
	country: 'get' | 'getById';
	document: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'delete';
	expiration: 'get' | 'getById';
	export: 'create' | 'getById';
	flexibleAssetField: 'get' | 'getById' | 'create' | 'update' | 'bulkUpdate' | 'destroy';
	flexibleAssetType: 'get' | 'getById' | 'create' | 'update' | 'delete';
	group: 'get';
	location: 'get' | 'getById' | 'create' | 'update' | 'delete';
	log: 'get';
	manufacturer: 'get' | 'getById' | 'create' | 'update' | 'delete';
	model: 'get' | 'getById' | 'create' | 'update' | 'delete';
	operatingSystem: 'get' | 'getById';
	organizationStatus: 'get' | 'getById' | 'create' | 'update';
	organizationType: 'get' | 'getById' | 'create' | 'update';
	passwordCategory: 'get' | 'getById' | 'create' | 'update';
	platform: 'get' | 'getById';
	region: 'get' | 'getById';
	relatedItem: 'get' | 'getById' | 'create' | 'update' | 'bulkDestroy' | 'delete';
	userMetric: 'get';
	user: 'get' | 'getById' | 'create' | 'update' | 'delete';
};

export type ITGlue = AllEntities<ITGlueMap>;

export type ITGlueConfiguration = Entity<ITGlueMap, 'configuration'>;
export type ITGlueDomain = Entity<ITGlueMap, 'domain'>;
export type ITGlueOrganization = Entity<ITGlueMap, 'organization'>;
export type ITGluePassword = Entity<ITGlueMap, 'password'>;
export type ITGlueFlexibleAsset = Entity<ITGlueMap, 'flexibleAsset'>;
export type ITGlueContact = Entity<ITGlueMap, 'contact'>;
export type ITGlueAttachment = Entity<ITGlueMap, 'attachment'>;
export type ITGlueConfigurationInterface = Entity<ITGlueMap, 'configurationInterface'>;
export type ITGlueConfigurationStatus = Entity<ITGlueMap, 'configurationStatus'>;
export type ITGlueConfigurationType = Entity<ITGlueMap, 'configurationType'>;
export type ITGlueContactType = Entity<ITGlueMap, 'contactType'>;
export type ITGlueCountry = Entity<ITGlueMap, 'country'>;
export type ITGlueDocument = Entity<ITGlueMap, 'document'>;
export type ITGlueExpiration = Entity<ITGlueMap, 'expiration'>;
export type ITGlueExport = Entity<ITGlueMap, 'export'>;
export type ITGlueFlexibleAssetField = Entity<ITGlueMap, 'flexibleAssetField'>;
export type ITGlueFlexibleAssetType = Entity<ITGlueMap, 'flexibleAssetType'>;
export type ITGlueGroup = Entity<ITGlueMap, 'group'>;
export type ITGlueLocation = Entity<ITGlueMap, 'location'>;
export type ITGlueLog = Entity<ITGlueMap, 'log'>;
export type ITGlueManufacturer = Entity<ITGlueMap, 'manufacturer'>;
export type ITGlueModel = Entity<ITGlueMap, 'model'>;
export type ITGlueOperatingSystem = Entity<ITGlueMap, 'operatingSystem'>;
export type ITGlueOrganizationStatus = Entity<ITGlueMap, 'organizationStatus'>;
export type ITGlueOrganizationType = Entity<ITGlueMap, 'organizationType'>;
export type ITGluePasswordCategory = Entity<ITGlueMap, 'passwordCategory'>;
export type ITGluePlatform = Entity<ITGlueMap, 'platform'>;
export type ITGlueRegion = Entity<ITGlueMap, 'region'>;
export type ITGlueRelatedItem = Entity<ITGlueMap, 'relatedItem'>;
export type ITGlueUserMetric = Entity<ITGlueMap, 'userMetric'>;
export type ITGlueUser = Entity<ITGlueMap, 'user'>;

export type ConfigurationProperties = PropertiesOf<ITGlueConfiguration>;
export type DomainProperties = PropertiesOf<ITGlueDomain>;
export type OrganizationProperties = PropertiesOf<ITGlueOrganization>;
export type PasswordProperties = PropertiesOf<ITGluePassword>;
export type FlexibleAssetProperties = PropertiesOf<ITGlueFlexibleAsset>;
export type ContactProperties = PropertiesOf<ITGlueContact>;
export type AttachmentProperties = PropertiesOf<ITGlueAttachment>;
export type ConfigurationInterfaceProperties = PropertiesOf<ITGlueConfigurationInterface>;
export type ConfigurationStatusProperties = PropertiesOf<ITGlueConfigurationStatus>;
export type ConfigurationTypeProperties = PropertiesOf<ITGlueConfigurationType>;
export type ContactTypeProperties = PropertiesOf<ITGlueContactType>;
export type CountryProperties = PropertiesOf<ITGlueCountry>;
export type DocumentProperties = PropertiesOf<ITGlueDocument>;
export type ExpirationProperties = PropertiesOf<ITGlueExpiration>;
export type ExportProperties = PropertiesOf<ITGlueExport>;
export type FlexibleAssetFieldProperties = PropertiesOf<ITGlueFlexibleAssetField>;
export type FlexibleAssetTypeProperties = PropertiesOf<ITGlueFlexibleAssetType>;
export type GroupProperties = PropertiesOf<ITGlueGroup>;
export type LocationProperties = PropertiesOf<ITGlueLocation>;
export type LogProperties = PropertiesOf<ITGlueLog>;
export type ManufacturerProperties = PropertiesOf<ITGlueManufacturer>;
export type ModelProperties = PropertiesOf<ITGlueModel>;
export type OperatingSystemProperties = PropertiesOf<ITGlueOperatingSystem>;
export type OrganizationStatusProperties = PropertiesOf<ITGlueOrganizationStatus>;
export type OrganizationTypeProperties = PropertiesOf<ITGlueOrganizationType>;
export type PasswordCategoryProperties = PropertiesOf<ITGluePasswordCategory>;
export type PlatformProperties = PropertiesOf<ITGluePlatform>;
export type RegionProperties = PropertiesOf<ITGlueRegion>;
export type RelatedItemProperties = PropertiesOf<ITGlueRelatedItem>;
export type UserMetricProperties = PropertiesOf<ITGlueUserMetric>;
export type UserProperties = PropertiesOf<ITGlueUser>;
