import { ConfigurationProperties } from "../../interfaces";

export const configurationGetDescription: ConfigurationProperties = [
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Page Number',
		name: 'pageNumber',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
		},
		default: 1,
		description: 'Page number for pagination (starts at 1)',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		description: 'Filter the configuration request',
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
			},
		},
	options: [
			{
				displayName: 'Archived',
				name: 'archived',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by archived status',
			},
			{
				displayName: 'Asset Tag',
				name: 'asset_tag',
				type: 'string',
				default: '',
				description: 'Filter by asset tag',
			},
			{
				displayName: 'Configuration ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Filter by specific configuration ID',
			},
			{
				displayName: 'Configuration Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Filter by configuration name',
			},
			{
				displayName: 'Configuration Status Name or ID',
				name: 'configuration_status_id',
				type: 'options',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				default: '',
				typeOptions: {
					loadOptionsMethod: 'getConfigurationStatuses',
				},
			},
			{
				displayName: 'Configuration Type Name or ID',
				name: 'configuration_type_id',
				type: 'options',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				default: '',
				typeOptions: {
					loadOptionsMethod: 'getConfigurationTypes',
				},
			},
			{
				displayName: 'Contact Name or ID',
				name: 'contact_id',
				type: 'options',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				default: '',
				typeOptions: {
					loadOptionsMethod: 'getContacts',
				},
			},
			{
				displayName: 'MAC Address',
				name: 'mac_address',
				type: 'string',
				default: '',
				description: 'Filter by MAC address',
			},
			{
				displayName: 'Organization Name or ID',
				name: 'organization_id',
				type: 'options',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				default: '',
				typeOptions: {
					loadOptionsMethod: 'getOrganizations',
				},
			},
			{
				displayName: 'PSA ID',
				name: 'psa_id',
				type: 'string',
				default: '',
				description: 'Filter by PSA ID (must be used with PSA Integration Type)',
			},
			{
				displayName: 'PSA Integration Type',
				name: 'psa_integration_type',
				type: 'options',
				options: [
					{ name: 'Autotask', value: 'autotask' },
					{ name: 'Kaseya BMS', value: 'kaseya-bms' },
					{ name: 'Manage', value: 'manage' },
					{ name: 'Pulseway PSA', value: 'pulseway-psa' },
					{ name: 'Tigerpaw', value: 'tigerpaw' },
					{ name: 'Vorex', value: 'vorex' },
				],
				default: 'manage',
				description: 'PSA integration type (required when using PSA ID)',
			},
			{
				displayName: 'RMM ID',
				name: 'rmm_id',
				type: 'string',
				default: '',
				description: 'Filter by RMM ID (must be used with RMM Integration Type)',
			},
			{
				displayName: 'RMM Integration Type',
				name: 'rmm_integration_type',
				type: 'options',
				options: [
					{ name: 'Addigy', value: 'addigy' },
					{ name: 'AEM', value: 'aem' },
					{ name: 'Atera', value: 'atera' },
					{ name: 'Automate', value: 'automate' },
					{ name: 'Auvik', value: 'auvik' },
					{ name: 'Continuum', value: 'continuum' },
					{ name: 'Jamf Pro', value: 'jamf-pro' },
					{ name: 'Kaseya VSA', value: 'kaseya-vsa' },
					{ name: 'LogMeIn', value: 'log-me-in' },
					{ name: 'Managed Workplace', value: 'managed-workplace' },
					{ name: 'Meraki', value: 'meraki' },
					{ name: 'MSP N-Central', value: 'msp-n-central' },
					{ name: 'MSP RMM', value: 'msp-rmm' },
					{ name: 'Ninja RMM', value: 'ninja-rmm' },
					{ name: 'Office 365', value: 'office365' },
					{ name: 'Panorama9', value: 'panorama9' },
					{ name: 'Pulseway RMM', value: 'pulseway-rmm' },
					{ name: 'Syncro', value: 'syncro' },
					{ name: 'VSA X', value: 'vsa-x' },
					{ name: 'Watchman Monitoring', value: 'watchman-monitoring' },
				],
				default: 'addigy',
				description: 'RMM integration type (required when using RMM ID)',
			},
			{
				displayName: 'Serial Number',
				name: 'serial_number',
				type: 'string',
				default: '',
				description: 'Filter by serial number',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
			},
		},
		default: {},
		options: [
			{
				displayName: 'Include',
				name: 'include',
				type: 'multiOptions',
				options: [
					{ name: 'Adapters Resources', value: 'adapters_resources' },
					{ name: 'Attachments', value: 'attachments' },
					{ name: 'Configuration Interfaces', value: 'configuration_interfaces' },
					{ name: 'DNET FA Remote Assets', value: 'dnet_fa_remote_assets' },
					{ name: 'Group Resource Accesses', value: 'group_resource_accesses' },
					{ name: 'Passwords', value: 'passwords' },
					{ name: 'RMM Records', value: 'rmm_records' },
					{ name: 'Tickets', value: 'tickets' },
					{ name: 'User Resource Accesses', value: 'user_resource_accesses' },
				],
				default: [],
				description: 'Related resources to include',
			},
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				options: [
					{ name: 'Created (Newest First)', value: '-created_at' },
					{ name: 'Created (Oldest First)', value: 'created_at' },
					{ name: 'ID (Highest First)', value: '-id' },
					{ name: 'ID (Lowest First)', value: 'id' },
					{ name: 'Name (A-Z)', value: 'name' },
					{ name: 'Name (Z-A)', value: '-name' },
					{ name: 'Updated (Newest First)', value: '-updated_at' },
					{ name: 'Updated (Oldest First)', value: 'updated_at' },
				],
				default: 'name',
				description: 'Sort order for results',
			},
		],
	},
];