import { ConfigurationProperties } from "../../interfaces";

export const configurationGetDescription: ConfigurationProperties = [
	{
		displayName: 'All Configurations',
		name: 'allconfigs',
		type: 'boolean',
		description: 'Whether to get all configurations or apply specific filtering',
		default: true,
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
			},
		},
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: {
			show: {
				resource: ['configuration'],
				operation: ['get'],
				allconfigs: [
					false,
				],
			},
		},
	options: [
			{
				displayName: 'Archived',
				name: 'archived',
				type: 'boolean',
				default: false,
				description: 'Whether to filter by archived status',
			},
			{
				displayName: 'Asset Tag',
				name: 'asset_tag',
				type: 'string',
				default: '',
				description: 'Filter by asset tag',
			},
			{
				displayName: 'Configuration ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Filter by specific configuration ID',
			},
			{
				displayName: 'Configuration Status ID',
				name: 'configuration_status_id',
				type: 'number',
				default: '',
				description: 'Filter by configuration status ID',
			},
			{
				displayName: 'Configuration Type ID',
				name: 'configuration_type_id',
				type: 'number',
				default: '',
				description: 'Filter by configuration type ID',
			},
			{
				displayName: 'Contact ID',
				name: 'contact_id',
				type: 'number',
				default: '',
				description: 'Filter by contact ID',
			},
			{
				displayName: 'Hostname',
				name: 'hostname',
				type: 'string',
				default: '',
				description: 'Filter by hostname',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				description: 'Max number of results to return',
				typeOptions: {
					minValue: 1,
				},
			},
			{
				displayName: 'Location ID',
				name: 'location_id',
				type: 'number',
				default: '',
				description: 'Filter by location ID',
			},
			{
				displayName: 'MAC Address',
				name: 'mac_address',
				type: 'string',
				default: '',
				description: 'Filter by MAC address',
			},
			{
				displayName: 'Manufacturer ID',
				name: 'manufacturer_id',
				type: 'number',
				default: '',
				description: 'Filter by manufacturer ID',
			},
			{
				displayName: 'Model ID',
				name: 'model_id',
				type: 'number',
				default: '',
				description: 'Filter by model ID',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				description: 'Filter by configuration name',
			},
			{
				displayName: 'Operating System ID',
				name: 'operating_system_id',
				type: 'number',
				default: '',
				description: 'Filter by operating system ID',
			},
			{
				displayName: 'Organization ID',
				name: 'organization_id',
				type: 'number',
				default: '',
				description: 'Filter by organization ID',
			},
			{
				displayName: 'Primary IP',
				name: 'primary_ip',
				type: 'string',
				default: '',
				description: 'Filter by primary IP address',
			},
			{
				displayName: 'Serial Number',
				name: 'serial_number',
				type: 'string',
				default: '',
				description: 'Filter by serial number',
			},
		],
	},
];